version: '3.4'

services:
  eventify.api:
    image: ${DOCKER_REGISTRY-}eventifyapi
    container_name: Eventify.Api
    build:
      context: src
      dockerfile: API/Eventify.Api/Dockerfile
    ports:
       - 5000:8080
       - 5001:8081 

  eventify.database:
    image: postgres:latest
    container_name: Eventify.Database
    environment:
      - POSTGRES_DB=eventify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  eventify.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: Eventify.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080


  eventify.seq:
    image: datalust/seq:latest
    container_name: Eventify.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  eventify.redis:
    image: redis:latest
    container_name: Eventify.Redis
    restart: always
    ports:
      - 6379:6379

  eventify.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Eventify.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

  eventify.queue:
    image: rabbitmq:management-alpine
    container_name: Eventify.Queue
    hostname: eventify-queue
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
 
